### ISSUE TITLE
Get Tagged OAuth not authorized

### ISSUE THREAD

**Issue by jonathanwiesel** [gregavola/tumblrPHP#3]
I'm having a problem making a OAuth request to the /tagged endpoint, I get the response "Not Authorized".

The code:

<pre>
$tumblr = new Tumblr($consumer,$secret,$userToken, $userSecret);
$params = array('tag' => 'lol', 'limit' => 5, 'filter' => 'text');
$taggedPosts = $tumblr->oauth_get('/tagged', $params);
</pre>

**Comment by gregavola** [comment]
I just pushed an update to the main lib folder that will allow to make these requests via basic Auth. Every attempt I get to call /tagged with OAuth results in a 401.

In the mean time - you can use basic example, to pull in tags and it should work as expected. Perhaps there is an error with documentation as I can make successful calls via the example in the project file.

Thanks,
Greg

**Comment by jonathanwiesel** [comment]
I've contacted Tumblr support for the matter, I've been trying other ways to hit that endpoint via OAuth, including via Postman (chrome extension) OAuth but always with the same result so I believe it should be something in Tumblr's side.

**Comment by jonathanwiesel** [comment]
Tumblr support never got back to me, in the past the just told me that probably the request parameters were not being used for signing the request:

> ...the issue is that the user/info request has no parameters, which is needed when signing the request but the tagged request does use parameters.
> 
> The OAuth library that you are using is not using the url parameters as part of the signature, so it's saying the request is invalid and throwing a 401 for you.

I debugged a little and found that the signature match the one using this tool:
http://oauth.googlecode.com/svn/code/javascript/example/signature.html

So I'm not sure what can be wrong

**Comment by jonathanwiesel** [comment]
According to Tumblr support the parameter array must have the api key parameter. Although the request will succeed with invalid tokens, with valid ones the rate limits will generally count against the user.
