### ISSUE TITLE
Typo in function name 'getAcessToken'

### ISSUE THREAD

**Issue by AbeCole** [gregavola/tumblrPHP#4]
Line 134 of 'tumblrPHP.php' the function is called 'getAcessToken' (notice 1 'c') and the examples show the proper spelling of 'getAccessToken'. Think maybe one 'c' character has been deleted from the class file.

**Comment by gilliek** [comment]
Come on guy, it's just a typo to fix...

**Comment by gregavola** [comment]
This should be fixed.

Greg

**Comment by gilliek** [comment]
Great, thanks :)
