### ISSUE TITLE
not authorized   [status] => 401

### ISSUE THREAD

**Issue by abhi23493** [gregavola/tumblrPHP#6]
After doing successful  authorization i am getting not authorized error! 
My code is exactly similar to your code. Please help!

**Comment by gregavola** [comment]
If your code is the same - then most likely there are incorrect keys provided - is there anyway you can provide the exact code you are using?

**Comment by abhi23493** [comment]
Ony blog/../info works. if i runn same with get_oath it gives me authorization error

$consumer = "my keys";
$secret = "my sec key";

$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

$oauth_verifier = $_GET['oauth_verifier'];

$token = $tumblr->getAccessToken($oauth_verifier);

$_SESSION['oauth_token'] = $token['oauth_token'];
$_SESSION['oauth_token_secret'] = $token['oauth_token_secret'];

$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

$followers = $tumblr->oauth_get("/blog/blog.untappd.com/followers");
print_r($followers);

**Comment by gregavola** [comment]
What does " if i runn same with get_oath it gives me authorization error" mean? Can you provide your code, what end point are you trying to call?

Greg

**Comment by abhi23493** [comment]
i tried to access  /blog/blog.untappd.com/followers with oauth_get method but in result i am getting authorization error

**Comment by gregavola** [comment]
So blog/.../info works - but /blog/.../followers doesn't work?

**Comment by abhi23493** [comment]
yeah that's what happening
blog/.../info only works with get method not bu oauth_get  :cry:

**Comment by gregavola** [comment]
Do you have sessions enabled on your PHP instance? I just tested this again, and everything works on this end. I would do a check to see if your sessions states are saved:

Make sure you have `sesssion_start()` on each page, you didn't have it on the code piece you mentioned. Maybe that could be it?

**Comment by abhi23493** [comment]
no session_start() is included in my code. I didnt mention it because it was very obvious. can you please post code of your callback.php with oauth_get call?

**Comment by gregavola** [comment]
```
session_start();

require ("tumblrPHP.php");

$consumer = "XXXXXXX";
$secret = "XXXXXXX";

$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

// The oauth_verfier is set back from Tumblr and is needed to obtain access tokens
$oauth_verifier = $_GET['oauth_verifier'];

// User the getAcessToken method and pass through the oauth_verifier to get tokens;
$token = $tumblr->getAccessToken($oauth_verifier);

// Set the session for the new access tokens, replacing the request tokens
$_SESSION['oauth_token'] = $token['oauth_token'];
$_SESSION['oauth_token_secret'] = $token['oauth_token_secret'];

// Create a new instance of the Tumblr Class with the Request Tokens that we just set at line 40 and 41
$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

// Grab the followers by using the oauth_get method.
$followers = $tumblr->oauth_get("/blog/blog.untappd.com/followers");

print_r($followers);
```

**Comment by gregavola** [comment]
If you still get errors - i would recommend out-putting the `$_SESSION` variable to make sure it contains everything you need.

Another good debugging area would be `$token` and doing a `print_r($token)` to make sure you are getting valid tokens.

Finally - make sure your consumer/secret keys are correct as well.

**Comment by abhi23493** [comment]
thanks for all your response and help . I will rectify mistakes and let you know if it is working.. thanks

**Comment by abhi23493** [comment]
Can i make calls to tumblr api by jQuery.ajax or php curl method if i have access_token and access secret ? if yes plz tell how..

**Comment by gregavola** [comment]
This is a repo for the PHP version of the TumblrAPI - so I'm not sure. You can certainly try using OAuth for JS, but it's not recommended for security reasons.

**Comment by abhi23493** [comment]
<?php

session_start();

include ("lib/tumblrPHP.php");

// Enter your Consumer / Secret Key:
$consumer = "6Gd0nt9JvJH4lzGgNRKb....................mRh5qXGGn";
$secret = "Min8QkUHCm3J2V31joZdKh3.....................nEf1qV";

$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

// The oauth_verfier is set back from Tumblr and is needed to obtain access tokens
$oauth_verifier = $_GET['oauth_verifier'];

// User the getAcessToken method and pass through the oauth_verifier to get tokens;
$token = $tumblr->getAccessToken($oauth_verifier);

// Set the session for the new access tokens, replacing the request tokens
$_SESSION['oauth_token'] = $token['oauth_token'];
$_SESSION['oauth_token_secret'] = $token['oauth_token_secret'];

// Create a new instance of the Tumblr Class with the Request Tokens that we just set at line 20 and 21
$tumblr = new Tumblr($consumer, $secret, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);

// Grab the followers by using the oauth_get method.
$followers = $tumblr->oauth_get("/blog/blog.untappd.com/followers");
print_r($followers);

?>

**Comment by gregavola** [comment]
That's correct - I would follow the steps I mentioned before about debugging and see what you get.

**Comment by abhi23493** [comment]
i checked $_SESSION and $token by printing them.. they are fine... my consumer and consumer_secret cant be wrong because i am getting successful callback .. still following response Object ( [meta] => stdClass Object ( [status] => 401 [msg] => Not Authorized ) [response] => Array ( ) )

**Comment by gregavola** [comment]
I would contact tumblr support for this issue - it appears that everything is working but either your account you are using or something deeper is causing an issue. Sorry I couldn't help more!

**Comment by dannyhtek** [comment]
Well there is a reason why you should not copy+paste any code without rechecking every single line. The problem you guys are having is the following line in the callback.php:

$followers = $tumblr->oauth_get("/blog/blog.untappd.com/followers");
print_r($followers);

Basically what you guys are trying to do is printing the followerslist of 'blog.untappd.com' while the blog hasn't signed in to your application. You have no permissions to do that. So here's the fix:

I run a blog (dannyhtek.tumblr.com) and thats also where I'm hosting my applications. After signing in and approving my own app, I get redirected to my callback.php and everything works fine, Why? Because I approved the app with MY tumblr and I'm requesting the followerslist of MY tumblr, using  the following line:

$followers = $tumblr->oauth_get("/blog/dannyhtek.tumblr.com/followers");

You see the difference? You obviously can not request the followerlist of a blog who hasnt signed in to your application as your application has no permissions to do that.
